FROM maven:3.9.9-eclipse-temurin-21 AS base
WORKDIR /app

COPY pom.xml .
COPY shared/pom.xml             ./shared/
COPY auth-service/pom.xml       ./auth-service/
COPY api-gateway/pom.xml        ./api-gateway/
COPY document-generator/pom.xml ./document-generator/
COPY document-worker/pom.xml    ./document-worker/
COPY storage-service/pom.xml    ./storage-service/
COPY template-service/pom.xml   ./template-service/

RUN mvn dependency:go-offline -B