server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
            - id: document-generator
              uri: http://document-generator:8082
              predicates:
                - Path=/api/documents/**

            - id: template-service
              uri: http://template-service:8083
              predicates:
                - Path=/api/templates/**

            - id: storage-service
              uri: http://storage-service:8084
              predicates:
                - Path=/api/storage/**


          default-filters:
            - StripPrefix=2
