server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2
            - id: auth-service-oauth2-callback
              uri: http://auth-service:8081
              predicates:
                - Path=/login/oauth2/code/**

            - id: document-generator
              uri: http://document-generator:8082
              predicates:
                - Path=/api/documents/**
              filters:
                - StripPrefix=2

            - id: template-service
              uri: http://template-service:8083
              predicates:
                - Path=/api/templates/**
              filters:
                - StripPrefix=2

            - id: storage-service
              uri: http://storage-service:8084
              predicates:
                - Path=/api/storage/**
              filters:
                - StripPrefix=2
jwt:
  secret: ${JWT_SECRET}