package com.legaldocsgpt.documentworker.service;

import com.legaldocsgpt.documentworker.exception.PdfGenerationException;
import com.legaldocsgpt.shared.client.StorageClient;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Slf4j
@Service
@RequiredArgsConstructor
public class PdfService {

    private final StorageClient storageClient;

    public String generatePdf(String jobId, String htmlContent) {
        log.info("Generating PDF for job: {}", jobId);

        String fullHtml = "<html><head><style>" +
                "body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 1in; line-height: 1.6; font-size: 11pt; color: #333; }" +
                "h3 { text-align: center; text-transform: uppercase; border-bottom: 1px solid #000; padding-bottom: 10px; margin-bottom: 30px; }" +
                "p { margin-bottom: 12px; text-align: justify; }" +
                "ul { margin-bottom: 10px; padding-left: 20px; }" +
                ".footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8pt; color: #777; }" +
                "</style></head><body>" +
                "<h3>Legal Document</h3>" +
                htmlContent +
                "<div class='footer'>Generated by LegalDocsGPT - Page 1</div>" +
                "</body></html>";

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(fullHtml, null);
            builder.toStream(baos);
            builder.run();

            byte[] pdfBytes = baos.toByteArray();
            log.info("PDF generated successfully ({} bytes). Uploading to storage...", pdfBytes.length);

            storageClient.uploadDocument(jobId, pdfBytes);

            return "/api/storage/docs/" + jobId + ".pdf";

        } catch (Exception e) {
            log.error("Failed to generate or upload PDF for job {}: {}", jobId, e.getMessage(), e);
            throw new PdfGenerationException("PDF engine failure: " + e.getMessage());
        }
    }
}